{
  lib,
  clan-core,
  config,
  ...
}:

let
  suffix = config.clan.core.vars.generators.disk-id.files.diskId.value;
in
{
  options = {
    disko.encryptedRoot = {
      enable = lib.mkOption {
        default = true;
        type = with lib.types; bool;
      };
    };
  };
  imports = [
    clan-core.clanModules.disk-id
  ];
  config = {
    # DO NOT EDIT THIS FILE AFTER INSTALLATION of a machine
    # Otherwise your system might not boot because of missing partitions / filesystems
    boot.loader.grub.efiSupport = lib.mkDefault true;
    boot.loader.grub.efiInstallAsRemovable = lib.mkDefault true;
    disko.devices = {
      disk = {
        "main" = {
          # suffix is to prevent disk name collisions
          name = "main-" + suffix;
          type = "disk";
          # Set the following in flake.nix for each maschine:
          # device = <uuid>;
          content = {
            type = "gpt";
            partitions = {
              "boot" = {
                size = "1M";
                type = "EF02"; # for grub MBR
                priority = 1;
              };
              "ESP" = {
                size = "1024M";
                type = "EF00";
                content = {
                  type = "filesystem";
                  format = "vfat";
                  mountpoint = "/boot";
                  mountOptions = [ "nofail" ];
                };
              };
              "root" = {
                size = "100%";
                content = {
                  type = "zfs";
                  pool = "zroot";
                };
              };
            };
          };
        };
      };

      zpool = {
        zroot = {
          type = "zpool";
          rootFsOptions =
            {
              acltype = "posixacl";
              atime = "off";
              compression = "zstd";
              mountpoint = "none";
              xattr = "sa";
            }
            // lib.mkIf (config.disko.encryptedRoot.enable) {
              encryption = "aes-256-gcm";
              keyformat = "passphrase";
              keylocation = "prompt";
            };
          #        postCreateHook = ''
          #          zfs set keylocation=prompt zroot;
          #        '';
          options.ashift = "12";
          options.cachefile = "none";

          datasets = {
            "local" = {
              type = "zfs_fs";
              options.mountpoint = "none";
            };
            "local/home" = {
              type = "zfs_fs";
              mountpoint = "/home";
              # Used by services.zfs.autoSnapshot options.
              options."com.sun:auto-snapshot" = "true";
            };
            "local/nix" = {
              type = "zfs_fs";
              mountpoint = "/nix";
              options."com.sun:auto-snapshot" = "false";
            };
            "local/persist" = {
              type = "zfs_fs";
              mountpoint = "/persist";
              options."com.sun:auto-snapshot" = "false";
            };
            "local/root" = {
              type = "zfs_fs";
              mountpoint = "/";
              options."com.sun:auto-snapshot" = "false";
              postCreateHook = "zfs snapshot zroot/local/root@blank";
            };
            "reserved" = {
              options = {
                mountpoint = "none";
                reservation = "50G";
              };
              type = "zfs_fs";
            };
          };
        };
      };
    };
  };
}
